# Generated by Django 5.2.8 on 2025-11-23 22:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'm_cargo',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'm_cliente',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'm_pais',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'm_producto',
            },
        ),
        migrations.CreateModel(
            name='TipoReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'm_tipo_reclamo',
            },
        ),
        migrations.CreateModel(
            name='TipoSolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'm_tipo_solucion',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100, null=True)),
                ('edad', models.PositiveIntegerField(null=True)),
                ('direccion_domicilio', models.CharField(max_length=255, null=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(max_length=15, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cargo')),
            ],
            options={
                'db_table': 'm_empleado',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_factura', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.empleado')),
            ],
            options={
                'db_table': 't_factura',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.producto')),
            ],
            options={
                'db_table': 'd_detalle_factura',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='app.pais')),
            ],
            options={
                'verbose_name': 'Provincia / Estado',
                'db_table': 'm_provincia',
                'unique_together': {('pais', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='app.provincia')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'db_table': 'm_ciudad',
                'unique_together': {('provincia', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('RESUELTO', 'Resuelto')], default='PENDIENTE', max_length=20)),
                ('descripcion_general', models.TextField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.factura')),
            ],
            options={
                'db_table': 't_reclamo',
            },
        ),
        migrations.CreateModel(
            name='DetalleReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_especifico', models.TextField()),
                ('evidencia_foto', models.FileField(blank=True, null=True, upload_to='evidencias/', verbose_name='Foto Evidencia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.producto')),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_reclamo', to='app.reclamo')),
                ('tipo_reclamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tiporeclamo')),
            ],
            options={
                'db_table': 'd_detalle_reclamo',
            },
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('sucursal', models.PositiveIntegerField(help_text='Número de sucursal (Ej: 1, 2, 3...)')),
                ('ubicacion', models.CharField(help_text='Calle principal, secundaria y número', max_length=200)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ciudad', verbose_name='Ubicación (Ciudad)')),
            ],
            options={
                'verbose_name': 'Restaurante / Sucursal',
                'db_table': 'm_restaurante',
                'unique_together': {('sucursal', 'ruc')},
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.restaurante'),
        ),
        migrations.CreateModel(
            name='Solucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('comentario_final', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(help_text='Empleado que cierra el caso', on_delete=django.db.models.deletion.PROTECT, to='app.empleado')),
                ('reclamo', models.OneToOneField(limit_choices_to=models.Q(('estado__in', ['PENDIENTE', 'EN_PROCESO'])), on_delete=django.db.models.deletion.PROTECT, related_name='solucion_general', to='app.reclamo')),
            ],
            options={
                'verbose_name': 'Solución (Cierre)',
                'db_table': 't_solucion',
            },
        ),
        migrations.CreateModel(
            name='DetalleSolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField()),
                ('detalle_reclamo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.detallereclamo')),
                ('solucion_general', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_solucion', to='app.solucion')),
                ('tipo_solucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tiposolucion')),
            ],
            options={
                'db_table': 'd_detalle_solucion',
            },
        ),
    ]
